spring:
  application:
    name: e-Commerce


  datasource:
    url: jdbc:postgresql://localhost:5432/learn_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

app:
  jwt:
    secret: bXktdmVyeS12ZXJ5LXZlcnktc2VjcmV0LWtleXdvcmQtZm9yLWp3dC1mb3ItYW1pbg==
    expiration: 300000
